"""changes because of adding shopify

Revision ID: 366cad3f6ab4
Revises: 90a04c68bbcd
Create Date: 2023-11-12 17:32:45.095212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '366cad3f6ab4'
down_revision: Union[str, None] = '90a04c68bbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #change table name
    op.rename_table('woocommerce_reviews', 'e_commerce_reviews')
    op.rename_table('woocommerce_clients', 'e_commerce_integrations')
    op.rename_table('woocommerce_orders', 'e_commerce_orders')


    #make the changes in the columns of e_commerce_integrations
    op.alter_column('e_commerce_integrations', 'wc_url', new_column_name='site_url',nullable=False)
    op.alter_column('e_commerce_integrations', 'consumer_key', new_column_name='wc_consumer_key',nullable=False)
    op.alter_column('e_commerce_integrations', 'consumer_secret', new_column_name='wc_consumer_secret',nullable=False)

    #create the columns in e_commerce_integrations as given in models
    op.add_column('e_commerce_integrations', sa.Column('s_private_token', sa.String(), nullable=True))
    op.add_column('e_commerce_integrations', sa.Column('s_judgeme_api_token', sa.String(), nullable=True))
    op.add_column('e_commerce_integrations', sa.Column('store_type', sa.String(), nullable=False, server_default=sa.text("'na'::character varying")))


    #make the changes in the columns 
    op.alter_column('e_commerce_reviews', 'reviewer', new_column_name='reviewer_name',nullable=True)
    op.alter_column('e_commerce_reviews', 'reviewer_email',nullable=True)
    op.alter_column('e_commerce_reviews', 'review',nullable=True,server_default='false')

    #create new columns
    op.add_column('e_commerce_reviews', sa.Column('date_updated', sa.TIMESTAMP(timezone=False), nullable=True))
    op.add_column('e_commerce_reviews', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('e_commerce_reviews', sa.Column('s_verified', sa.String(), nullable=True))
    op.add_column('e_commerce_reviews', sa.Column('store_type', sa.String(), nullable=False, server_default=sa.text("'na'::character varying")))


    #make the changes in the columns of e_commerce_orders
    op.alter_column('e_commerce_orders', 'status', new_column_name='financial_status',nullable=True)
    op.alter_column('e_commerce_orders', 'date_modified',nullable=True)
    op.alter_column('e_commerce_orders', 'first_name',nullable=True)
    op.alter_column('e_commerce_orders', 'last_name',nullable=True)
    op.alter_column('e_commerce_orders', 'address_1',nullable=True)
    op.alter_column('e_commerce_orders', 'address_2',nullable=True)
    op.alter_column('e_commerce_orders', 'city',nullable=True)
    op.alter_column('e_commerce_orders', 'state',nullable=True)
    op.alter_column('e_commerce_orders', 'postcode',nullable=True)
    op.alter_column('e_commerce_orders', 'country',nullable=True)
    op.alter_column('e_commerce_orders', 'phone',nullable=True)
    op.alter_column('e_commerce_orders', 'email',nullable=True)
    op.alter_column('e_commerce_orders', 'payment_method',nullable=True)
    op.alter_column('e_commerce_orders', 'customer_note',nullable=True)
    

    #create new columns in e_commerce_orders
    op.add_column('e_commerce_orders', sa.Column('store_type', sa.String(), nullable=False, server_default=sa.text("'na'::character varying")))
    op.add_column('e_commerce_orders', sa.Column('s_cancelled_at', sa.TIMESTAMP(timezone=False), nullable=True))
    op.add_column('e_commerce_orders', sa.Column('s_cancel_reason', sa.String(), nullable=True))
    op.add_column('e_commerce_orders', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('e_commerce_orders', sa.Column('s_fulfillment_status', sa.String(), nullable=True))
    



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    #change table name
    op.rename_table('e_commerce_reviews', 'woocommerce_reviews')
    op.rename_table('e_commerce_integrations', 'woocommerce_clients')
    op.rename_table('e_commerce_orders', 'woocommerce_orders')


    #make the changes in the columns of e_commerce_integrations
    op.alter_column('woocommerce_clients', 'site_url', new_column_name='wc_url',nullable=False)
    op.alter_column('woocommerce_clients', 'wc_consumer_key', new_column_name='consumer_key',nullable=False)
    op.alter_column('woocommerce_clients', 'wc_consumer_secret', new_column_name='consumer_secret',nullable=False)

    #drop the columns in e_commerce_integrations as given in models
    op.drop_column('woocommerce_clients', 's_private_token')
    op.drop_column('woocommerce_clients', 's_judgeme_api_token')
    op.drop_column('woocommerce_clients', 'store_type')


    #make the changes in the columns
    op.alter_column('woocommerce_reviews', 'reviewer_name', new_column_name='reviewer',nullable=True)
    op.alter_column('woocommerce_reviews', 'reviewer_email',nullable=True)
    op.alter_column('woocommerce_reviews', 'review',nullable=True,server_default='false')

    #drop new columns
    op.drop_column('woocommerce_reviews', 'date_updated')
    op.drop_column('woocommerce_reviews', 'hidden')
    op.drop_column('woocommerce_reviews', 's_verified')
    op.drop_column('woocommerce_reviews', 'store_type')


    #make the changes in the columns of e_commerce_orders
    op.alter_column('woocommerce_orders', 'financial_status', new_column_name='status',nullable=True)
    op.alter_column('woocommerce_orders', 'date_modified',nullable=True)
    op.alter_column('woocommerce_orders', 'first_name',nullable=True)
    op.alter_column('woocommerce_orders', 'last_name',nullable=True)
    op.alter_column('woocommerce_orders', 'address_1',nullable=True)
    op.alter_column('woocommerce_orders', 'address_2',nullable=True)
    op.alter_column('woocommerce_orders', 'city',nullable=True)
    op.alter_column('woocommerce_orders', 'state',nullable=True)
    op.alter_column('woocommerce_orders', 'postcode',nullable=True)
    op.alter_column('woocommerce_orders', 'country',nullable=True)
    op.alter_column('woocommerce_orders', 'phone',nullable=True)
    op.alter_column('woocommerce_orders', 'email',nullable=True)
    op.alter_column('woocommerce_orders', 'payment_method',nullable=True)
    op.alter_column('woocommerce_orders', 'customer_note',nullable=True)


    #drop new columns in e_commerce_orders
    op.drop_column('woocommerce_orders', 'store_type')
    op.drop_column('woocommerce_orders', 's_cancelled_at')
    op.drop_column('woocommerce_orders', 's_cancel_reason')
    op.drop_column('woocommerce_orders', 'currency')
    op.drop_column('woocommerce_orders', 's_fulfillment_status')

    # ### end Alembic commands ###
