"""add delete_cursed_words column to woocommerce_clients table

Revision ID: 90a04c68bbcd
Revises: 34abd60f3cd7
Create Date: 2023-10-27 10:31:40.357432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90a04c68bbcd'
down_revision: Union[str, None] = '34abd60f3cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('woocommerce_clients', sa.Column('delete_cursed_words', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('woocommerce_clients', 'delete_cursed_words')
    pass
    # ### end Alembic commands ###
