"""create a prices column and sku column  in woocommerce_orders table

Revision ID: b970661e5bc7
Revises: 94f7421c828f
Create Date: 2023-10-25 20:59:45.578804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b970661e5bc7'
down_revision: Union[str, None] = '94f7421c828f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('woocommerce_orders', sa.Column('prices', postgresql.ARRAY(sa.Float()), nullable=False, server_default=sa.text('ARRAY[]::double precision[]')))
    op.add_column('woocommerce_orders', sa.Column('sku', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text('ARRAY[]::text[]')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('woocommerce_orders', 'sku')
    op.drop_column('woocommerce_orders', 'prices')
    # ### end Alembic commands ###
