"""create woocommerce_orders table

Revision ID: eba7710ce55f
Revises: b7ed4c38d843
Create Date: 2023-10-14 09:32:40.371859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eba7710ce55f'
down_revision: Union[str, None] = 'b7ed4c38d843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woocommerce_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_modified', sa.TIMESTAMP(), nullable=False),
    sa.Column('total', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('customer_note', sa.String(), nullable=True),
    sa.Column('line_items', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('quantity', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['woocommerce_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    pass
                    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('woocommerce_orders')
    pass
    # ### end Alembic commands ###
